//------->>>> EMAIL OTP <<<<----------//

export const EMAIL_OTP_STATUS_RESET = "EMAIL_OTP_STATUS_RESET";
export const EMAIL_OTP_VARIFY_STATUS_RESET = "EMAIL_OTP_VARIFY_STATUS_RESET";
export const EMAIL_FORGOT_OTP_STATUS_RESET = "EMAIL_FORGOT_OTP_STATUS_RESET";
export const GET_EMAIL_OTP = "GET_EMAIL_OTP";
export const VALIDATE_EMAIL_OTP = "VALIDATE_EMAIL_OTP";
export const EMAIL_OTP_START = "EMAIL_OTP_START";
export const EMAIL_OTP_SUCCESS = "EMAIL_OTP_SUCCESS";
export const EMAIL_OTP_FAIL = "EMAIL_OTP_FAIL";
//-------------->>>>>>>>>> PASSWORD REGISTER <<<<<<<<<---------------//
export const PASSWORD_REGISTER_START = "PASSWORD_REGISTER_START";
export const PASSWORD_REGISTER_SUCCESS = "PASSWORD_REGISTER_SUCCESS";
export const PASSWORD_REGISTER_FAIL = "PASSWORD_REGISTER_FAIL";
export const SAVE_PASSWORD_REGISTER = "SAVE_PASSWORD_REGISTER";
export const FORGOT_PASSWORD_OTP = "FORGOT_PASSWORD_OTP";
export const FORGOT_PASSWORD_OTP_FAIL = "FORGOT_PASSWORD_OTP_FAIL";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

//-------------->>>>>>>>>> LOGIN <<<<<<<<<---------------//
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

//-------------->>>>>>>>>> USER  <<<<<<<<<---------------//
export const ADD_OFFICE_EXPENSE = "ADD_OFFICE_EXPENSE";
export const GET_OFFICE_EXPENSE = "GET_OFFICE_EXPENSE";
export const OFFICE_EXPENSE_FILTER = "OFFICE_EXPENSE_FILTER";
export const GET_USER_SEARCH = "GET_USER_SEARCH";

export const ADD_USER_BOOKING = "ADD_USER_BOOKING";
export const GET_USER_BOOKING = "GET_USER_BOOKING";
export const USER_BOOKING_FILTER = "USER_BOOKING_FILTER";

export const ADD_USER_PAYMENT = "ADD_USER_PAYMENT";
export const GET_USER_PAYMENT = "GET_USER_PAYMENT";
export const USER_PAYMENT_FILTER = "USER_PAYMENT_FILTER";

export const GET_USER_VISIT = "GET_USER_VISIT";
export const ADD_USER_VISIT = "ADD_USER_VISIT";
export const USER_VISIT_FILTER = "USER_VISIT_FILTER";


